### ISSUE TITLE
关于公式4的distance indicator

### ISSUE THREAD

**Issue by xyl-507** [Garyson1204/HGINet#1]
感谢作者的贡献。

我想请问一下，公式4中的distance indicator这部分在代码的什么地方呀? 我在[  def forward(self, x, ret_attn_mask=False):](https://github.com/Garyson1204/HGINet/blob/9ee819229a29f053fb3c53c00bd1dfae4beb6149/bra_legacy.py#L224) 这部分中没有找到。

十分感谢

**Comment by Garyson1204** [comment]
Hello,

Thanks for your interest in our work.

Please check [HGINet/bra_legacy.py#L62C1-L76C71](https://github.com/Garyson1204/HGINet/blob/9ee819229a29f053fb3c53c00bd1dfae4beb6149/bra_legacy.py#L62C1-L76C71)
The distance indicator is represented by `dist` in line 72.

**Comment by xyl-507** [comment]
Very interesting work! 
Looking forward to its early publication.
